export interface ITheme {
  background100: string,
  background200: string,
  card100: string,
  card200: string,
  darkShadow: string,
  lightShadow: string,
  primmary: string,
  primmary100: string,
  primmary200: string,
  color100: string,
  color200: string,
  color300: string,
  color400: string,
  fontSize: {
    xs: string, 
    s: string,
    m: string,
    l: string,
    xl: string,
  },
 }